### ISSUE TITLE
ktx 한 구간 선택시 soldout 에러

### ISSUE THREAD

**Issue by 54ma34** [lapis42/srtgo#11]
![11](https://github.com/user-attachments/assets/72632d6e-eebc-4320-87e5-f704209eabfa)
![22](https://github.com/user-attachments/assets/6cdfff20-500e-4bfa-8f9d-73015cbf8c32)
안녕하세요 먼저 저 같은 초보 비전공자도 사용하기 쉽게 만들어주셔서 정말 감사드립니다.
가족이 주기적으로 서울 병원에 가야 하는데 덕분에 정말 유용하게 사용할 것 같습니다.

다름이 아니라 ktx 예매시 열차편성 1개만 선택하면 사진과 같은 soldout 에러가 뜹니다.
2개이상 선택시 정상적으로 예매시도가 되구요 혹시 제가 뭘 놓친 부분이 있는지 궁금합니다.

**Comment by lapis42** [comment]
- 피드백 감사드립니다. 제가 KTX를 잘 쓰지 않다보니 놓친 것 같습니다.
- 1.3.9로 업데이트 하였습니다 `pip install srtgo -U`를 실행하여 1.3.9로 업데이트 되는지 확인 부탁드립니다.
