### ISSUE TITLE
새마을 예매시도하니 에러메시지가 나왔습니다.

### ISSUE THREAD

**Issue by Lskyz** [lapis42/srtgo#12]
Exception: Sold out (None), Type: <class 'korail2.korail2.SoldOutError'>, Args: (), Message: Sold out

에러가 뜨고 계속 할까요 y/n 라는 메시지가 시도할 때마다 뜹니다.

**Comment by lapis42** [comment]
알려주셔서 감사합니다.
#11 Sold out error 대응 코드 추가하였습니다.
