### ISSUE TITLE
건의드려봅니다!

### ISSUE THREAD

**Issue by TSky99** [lapis42/srtgo#13]
구글 서치하다가 .텔레그램 봇으로 srtgo py파일 스크립트를 호출해서  대화형 형식으로 메시지를 주고 받을 수 있는 python-telegram-bot 라이브러리가 있다는것을 알게되었는데  그러면 폰으로  편리하게 예약 할 수 있을 것 같아 건의드려봅니다..

**Comment by lapis42** [comment]
python-telegram-bot은 현재 module에 포함되어 있기도 하나, 모바일로의 구현은 조금 어려울 듯 합니다 (모바일 예매 앱은 이미 다른 분이 만들어놓으신 것도 있습니다)...
