### ISSUE TITLE
경로우대 에러

### ISSUE THREAD

**Issue by zwl051000** [lapis42/srtgo#15]
![image](https://github.com/user-attachments/assets/acbf2464-e5cb-4e41-9255-ae6e183cfffa)

SRT 경로 1명 예약했을때 이미지와 같이 에러가 뜨네요. 확인 좀 부탁드려도 될까요? 항상 감사드립니다~ ^^

**Comment by lapis42** [comment]
현재 SRT module (https://github.com/ryanking13/SRT)은 경로 예약이 되지 않습니다. 만일 경로를 예약하려면 수정된 SRT를 따로 설치 (`pip install git+https://github.com/lapis42/SRT`)하셔야 합니다.

그렇지 않다면 성인으로 예매 후 홈페이지에서 예약변경하시는 것을 추천합니다.

**Comment by lapis42** [comment]
```
pip install git+https://github.com/lapis42/srtgo
pip install git+https://github.com/lapis42/SRT
```
이렇게 업데이트 후 정상 작동하는 것 확인하였습니다.

**Comment by zwl051000** [comment]
진짜 천재이신것 같아요. 잘 됩니다. 너무너무 감사합니다.
