### ISSUE TITLE
역 추가 문의

### ISSUE THREAD

**Issue by jangh-lee** [lapis42/srtgo#17]
추가하고 싶은 역이 있는데 코드를 로컬에서 수정하고 돌려도 반영이 안되네요?
어떻게 하면 될까요?

**Comment by lapis42** [comment]
원하시는 역이 있으시면 `STATIONS` 변수에 추가하시고, 메뉴에서 **역 설정**에 들어가서 역을 추가해주어야 합니다. 이렇게 한 후에도 반영이 되지 않으면 알려주십시오.

**Comment by jangh-lee** [comment]
오 답변 감사합니다!!

지금처럼 STATIONS에 청도를 추가해 변수를 수정했으나 반영되지 않아서 반영절차가 별도로 있는지 궁금하네요.
바이너리를 별도로 빌드하거나 해야하는지요?

혹시나해서 '서울'을 '서1울'로 변경해보아도 반영되지 않습니다.

![image](https://github.com/user-attachments/assets/40c027a8-928d-4725-af10-5b8a69c3663d)

**Comment by lapis42** [comment]
수정한 코드를 실행하기 위해서 1) `python -m srtgo.srtgo` 혹은 `python -m srtgo`으로 하시거나 2) `pip install .` 하셔서 수정한 코드로 업데이트 후 `srtgo`를 실행하셔야 합니다.

**Comment by jangh-lee** [comment]
잘 실행됩니다. 정말 감사합니다. 너무 잘 만들어져있네요.
