### ISSUE TITLE
혹시 이 에러 어떻게 해결해야 할지 문의드립니다.

### ISSUE THREAD

**Issue by zwl051000** [lapis42/srtgo#19]
첨부 이미지 확인 부탁드립니다.
어떤게 문제인지 모르겠습니다. ㅡㅜ

![image](https://github.com/user-attachments/assets/47648562-f3b3-4155-a569-93dae2f5f3bc)

**Comment by lapis42** [comment]
1) `pip install git+https://github.com/lapis42/SRT`로 설치를 하신게 맞는지요? srtgo 업데이트 후에는 다시 설치 해주어야 합니다. 
2) 경로 우대 대신에 성인으로 구입을 해도 계속 에러가 나는지요? 

제 환경에서는 성인/경로 모두 예약/결제 문제 없이 진행되고 있습니다.

**Comment by zwl051000** [comment]
감사합니다. 1번으로 해결이 되었습니다. ^^
