### ISSUE TITLE
예약 성공시 텔레그램 메시지 송신 및 무한 예약 이슈

### ISSUE THREAD

**Issue by wikithom91** [lapis42/srtgo#2]
- 예약 성공시 텔레그램으로 성공과 관련한 메시지를 송신하지 않습니다. 이전 버전에서는 잘 사용했었습니다. SRTGO 텔레그램 설정 완료 등 메시지는 수신했습니다.
- 예약 완료시 예약을 위한 탐색을 멈추는 것이 아닌 무한반복하여 예약을 탐색하고 예약을 하는 오류가 있습니다

**Comment by lapis42** [comment]
네 제가 결제 기능만 제외하고 테스트를 했었는데 결제 부분에서 막히는 것 같습니다. 우선 결제 제외하고 예매를 진행하시고, 해결되는 대로 업데이트 하겠습니다.

**Comment by wikithom91** [comment]
안녕하세요! 업데이트 및 카드 정보 수정으로 srt 정상 예매는 확인하였습니다
 KTX의 경우 예약 되었다는 텔레그램은 수신하였으나, 코레일 접속 후 예매 리스트를 확인하니 보이지 않습니다
한번 확인부탁드립니다
