### ISSUE TITLE
SRT 결제에 법인카드 요청

### ISSUE THREAD

**Issue by 93cy** [lapis42/srtgo#20]
혹시, 결제할 때, 법인카드도 가능하도록 수정 가능 할까요 ?

**Comment by lapis42** [comment]
`pip install git+https://github.com/lapis42/srtgo`로 설치 후에 테스트 결과를 알려주실 수 있으신지요. 생년월일 대신에 사업자번호를 입력하셔야 합니다.

**Comment by 93cy** [comment]
잘 됩니다. 감사합니다.

**Comment by lapis42** [comment]
감사합니다
