### ISSUE TITLE
실행관련 문의드리고 싶습니다

### ISSUE THREAD

**Issue by haezzo** [lapis42/srtgo#21]
매크로를 찾다가 파이썬 파일로 된 매크로를 찾게 되었습니다
파이썬에 대해 하나도 모르지만 파이썬 설치 후 매크로를 실행하였는데
팝업창 하나가 뜬 후 1초만에 사라집니다
어떻게 실행하는지 정말 궁금합니다

**Comment by lapis42** [comment]
1. 아나콘다나 미니콘다를 설치 (https://www.anaconda.com/download/success) 후
2. Anaconda Prompt를 실행하시고, `pip install srtgo -U`를 입력하여 아나콘다 환경에 srtgo를 설치합니다.
3. 이후 srtgo로 실행하시면 됩니다.
