### ISSUE TITLE
SRT 현재 사용불가능합니다.

### ISSUE THREAD

**Issue by wjdghks7600** [lapis42/srtgo#25]
![image](https://github.com/user-attachments/assets/caa69aa1-492e-4ee5-b5fc-1c5179731748)

SRT 현재 사용불가능합니다.

**Comment by tph00300** [comment]
저도 동일하게 불가능합니다. SRT 측에서 API 구조가 변경된건가요...!

**Comment by lapis42** [comment]
현재 SRT API가 정상 작동하지 않습니다. ryanking13/SRT#272

`pip install git+https://github.com/lapis42/srtgo`
로 업데이트하면 현재 사용은 가능하나 아직 예매 중에 에러가 간혹 발생합니다.
