### ISSUE TITLE
매진된 경우는 사용할 수 없나요?

### ISSUE THREAD

**Issue by JH-JasonHong** [lapis42/srtgo#26]
매진된 편에 적용해보려니 "예약 가능한 열차가 없습니다" 가 뜨고 반복실행은 안되는데, 제가 사용법을 몰라서 안 되는건지 지원이 안되는건지 몰라서 여쭙습니다. 감사합니다.

KTX로 해보니 KTX에서는 정상동작하네요. SRT는 현시간 동작이 안 되는듯합니다. 막힌걸까요?

**Comment by wjdghks7600** [comment]
SRT 현재 오류가 있어보입니다.

**Comment by ktr218** [comment]
SRT 최근 대량 접속으로 인한 점검과정에서 매크로사용 막기위해 서버 우회로를 막은것같습니다.

**Comment by lapis42** [comment]
v1.4.2로 업데이트 하였습니다. KTX 예매의 경우 증상을 자세히 알려주시면 확인하도록 하겠습니다.
