### ISSUE TITLE
사용법 설명 한번 가능하실까요.

### ISSUE THREAD

**Issue by Giruggu560** [lapis42/srtgo#27]
안에 들어있음 README 자료를 보긴 했는데 따라해도 실행이 되지 않습니다.

도움 한번 부탁드립니다.

![화면 캡처 2024-12-11 184040](https://github.com/user-attachments/assets/2cdb708b-07d1-4e35-a32f-a7291abb352c)

**Comment by lapis42** [comment]
1. 아나콘다나 미니콘다 등 파이선 환경을 설치하신 후
2. `pip install srtgo -U` 명령어로 srtgo 패키지를 설치하고
3. `srtgo`로 실행하시면 됩니다.

**Comment by Giruggu560** [comment]
감사합니다 개발자님
주말부부인데 원래 쓰던게 막혀서 고민중이었는데 고맙습니다.
작지만 연말 따뜻하게 보내세요





2024년 12월 12일 (목) 오후 6:27, DKim ***@***.***>님이 작성:
