### ISSUE TITLE
에러 해결 도움 부탁드립니다....ㅠ

### ISSUE THREAD

**Issue by wkrkd3716** [lapis42/srtgo#29]
SRT 예매시 "선택한 열차가 없습니다" 오류도 API 이슈일까요? 뭔가 더 세팅이 필요한걸까요?

감사합니다...!

![image](https://github.com/user-attachments/assets/601e3e56-4908-40fa-86f3-2bf2dc824e57)

**Comment by lapis42** [comment]
스페이스를 눌러 열차를 선택해야 합니다.
