### ISSUE TITLE
사용법 문의드립니다.

### ISSUE THREAD

**Issue by toray7** [lapis42/srtgo#30]
글 보고 안내해주신대로 해봤는데 실행이 안되네요.
확인 부탁드립니다.
![1](https://github.com/user-attachments/assets/8c00f4a0-515d-4779-b4be-5205e23efb6c)

**Comment by lapis42** [comment]
파이썬과 아나콘다 가상환경 두 곳에 분산되어 설치된 것 같습니다. 둘 중 하나를 제거하시고 다시 설치 후 확인해주십시오.
