### ISSUE TITLE
ktx 예약목록 앱확인불가

### ISSUE THREAD

**Issue by seunghyoYOO** [lapis42/srtgo#31]
안녕하세요 
먼저 감사의 말씀드립니다.
이제 코딩을 배우고 있는 비전공자로써 공유해주신 소스코드를 보면서 많이 이용하고 또 배우고 있습니다. 

다시한번 감사드립니다.

다름이아니라 KTX 의 경우 파이썬 터미널에서 예약확인이 완료된걸로 나오는데 앱에서는 예약항목이 확인되지 않습니다.

관련자료를 찾다보니 기기마다 있는 UUID? 값? 을확인해서 예매했던 값과 조회값이 다르면 표출되지않는 다는 문서를 확인했는데

그 이유 때문인건지 모르겠지만 저는 예약이 완료되어도 모바일앱에서 예약목록 확인이 안되더라구요,
이게 저만의 상황에서 문제인지 아니면 공통 문제인지 여쭤보고 싶어서 글남깁니다.

참고로 최근 netfunnel 이슈 전에도 동일했었습니다

감사합니다

**Comment by lapis42** [comment]
코레일톡 앱 매뉴 > 승차권 예매 > 예약 승차권 조회 취소 에서 확인하십시오.
나의 티켓에서는 발권된 승차권만 조회할 수 있습니다.

**Comment by seunghyoYOO** [comment]
에구.. 너무 말도안되는 질의 였네요 감사합니다 !
