### ISSUE TITLE
SRT 로그인 필요 오류

### ISSUE THREAD

**Issue by Mocoping2** [lapis42/srtgo#32]
![Screenshot_20241214_141804_Telegram](https://github.com/user-attachments/assets/8eff1598-a769-4261-83e9-43ac1eeede6c)

업데이트후 이런 현상이 나오는 거 같습니다.

로그인이 필요하다고 뜨는데 막상 로그인 설정 및 예약 확인하면 제대로 로그인이 되있습니다.

매 번 이러는 게 아니라 어쩔 땐 예매가 잘 되고 어쩔 땐 저 메시지가 뜨는 거 같습니다.

항상 잘 이용하고 있습니다. 감사합니다.

**Comment by lapis42** [comment]
로그아웃 에러 시 다시 로그인을 시도하도록 변경하였습니다.
