### ISSUE TITLE
안녕하세요 코레일 KTX 작동이 안됩니다

### ISSUE THREAD

**Issue by gungyesound** [lapis42/srtgo#33]
![스크린샷 2024-12-14 183318](https://github.com/user-attachments/assets/afba89b0-20ff-43eb-9d2b-19d3c38a383c)

안녕하세요 만들어주신거 받아서 파이썬에서 사용하고 있습니다

자리가 비어있을때는 텔레그램 알람도 오고 잘되는데 매진이 된 상태에서 사용할경우

실제 자리가 생겼음에도 예매못하고 대기중에서 계속 시간만 경과합니다 혹시 어떻게 해결할수있는지 알수있을까요

**Comment by lapis42** [comment]
열차를 1개만 선택하였을 경우, 빠른 진행을 위하여 search를 진행하지 않고 바로 예매를 시도하도록 하였는데, KTX의 경우에는 예매 시도를 진행하지 않는 문제가 있어 KTX 코드를 내부화하면서 동시에 수정하였습니다.
