### ISSUE TITLE
예매 시 오류 문의

### ISSUE THREAD

**Issue by orangefirstlove** [lapis42/srtgo#35]
안녕하세요. 개발자님.

지난번 명절 이후 또 문의 남기게 되었습니다. 항상 잘 쓰고 있습니다.

다름이아니라 스크린샷 같은 오류가 발생하고 있습니다.

![스크린샷 2024-12-15 235223](https://github.com/user-attachments/assets/54f43323-1a0f-435b-aa71-5b7fa6a7fb35)

텔레그램으로도 아래와 같은 오류 메시지가 도착했습니다.

![스크린샷 2024-12-15 235458](https://github.com/user-attachments/assets/6ae51e00-ba4c-4f88-8487-6360a18ac3bb)

지난 이슈 게시글을 읽어보고

pip install git+https://github.com/lapis42/srtgo

pip install git+https://github.com/lapis42/SRT

둘 다 해보고

pip install srtgo -U 역시 해봤는데

동일한 오류가 자꾸 발생합니다 ㅜㅜ

각자 다른 2대의 컴퓨터에서 해봤는데도 이런 증상이 나오네요..

혹시 제 개인 환경 문제인지 .. 궁금합니다.

날씨가 춥네요. 감기 조심하시고 항상 행복하시길 바랍니다. 감사합니다.

**Comment by lapis42** [comment]
안녕하세요. 제 환경에서는 재현이 어렵기도 하고 최근에 코드를 너무 많이 수정해서;;
1) 가장 최신 버전으로 업데이트 해주시고 (`pip install git+https://github.com/lapis42/srtgo -U`)
2) SRT인지 KTX인지
3) 열차 몇 대를 예매신청하셨는지 (1대와 여러대가 조금 다릅니다)
4) 발생 시기 및 빈도를 알려주시면 감사하겠습니다.

**Comment by Rogerlee241** [comment]
(그나저나 개발자님 고생이 너무 많으십니다. 감사합니다.)

**Comment by orangefirstlove** [comment]
1. 최신버전 업데이트 이후에도 동일합니다. 본문에도 남겼다시피 제 회사에 있는 컴퓨터, 집에 있는 컴퓨터 둘 다 동일합니다.
2. SRT 입니다.
3. 열차 1대만 했습니다.
4. 발생 시기 및 빈도는 항상 저렇습니다. 저게 열차가 생겨 잡았는데 저런 오류가 뜨는건지, 잡지 못해도 간헐적으로 뜨는건지는 확인 불가능합니다.

**Comment by lapis42** [comment]
Commit [0d3be27](https://github.com/lapis42/srtgo/commit/0d3be2782d49c4b81810316db8a97615f551ffa6) 참고 부탁드립니다.
1주일 정도 후에 v2.0.0으로 publish 하겠습니다.

**Comment by orangefirstlove** [comment]
빠른 피드백 및 답변 감사드립니다. 써보고 문제생기면 다시 부탁드리겠습니다. 감사합니다. 좋은 하루 보내세요^^

**Comment by orangefirstlove** [comment]
조치해주시고 잘 예약 되고 있습니다. 다시 한 번 감사드립니다^^
