### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by daniel00** [lapis42/srtgo#36]
예매 시도 후 일정 시간 진행 후 아래의 익셉션이 발생하네요.
발생 시간은 랜덤 합니다.
맥북 사용중이고 와이파이로 접속중입니다. 감사합니다.

Exception: Expecting value: line 1 column 1 (char 0), Type: <class 'json.decoder.JSONDecodeError'>, Args: ('Expecting value: line 1 column 1 (char 0)',), Message: Expecting value

**Comment by lapis42** [comment]
#35 와 동일한 문제로 [0d3be27](https://github.com/lapis42/srtgo/commit/0d3be2782d49c4b81810316db8a97615f551ffa6)로 해결
