### ISSUE TITLE
예매 대기 중 시 잔여석 없음 문제

### ISSUE THREAD

**Issue by orangefirstlove** [lapis42/srtgo#4]
안녕하세요. 항상 잘 쓰다가 처음으로 글을 남기게 됐습니다.

덕분에 편하게 고향에 가게되어 항상 감사함을 느끼며 사용하고 있습니다. 감사합니다.

업데이트 이후인거같은데 예매 시 카드결제 단계에서 N 을 입력하고

예매 대기중에서 잔여석없음으로 넘어가면

기존에는 예매가 될때까지 계속 시도했는데

업데이트 이후 계속할까요 (Y/N) 이 나와서 예매시도가 제대로 작동하지 않고 있습니다.

![12121](https://github.com/user-attachments/assets/6c720d56-e32c-486a-a058-af31cf904d6f)

제가 사용법을 잘못아는건지 해서 혹시 몰라 문의 남겨봅니다.

행복한 추석 보내시고 항상 건강하시길 바랍니다. 감사합니다.

**Comment by lapis42** [comment]
네 다른 에러에 대처하다보니 잔여석없음 에러를 놓쳤네요. 다시 변경해서 업데이트 하겠습니다

**Comment by orangefirstlove** [comment]
감사합니다^^

**Comment by lapis42** [comment]
v1.3.5로 수정하였습니다. `pip install srtgo -U`로 버전이 1.3.5로 올라가는지 확인해주세요~.

**Comment by orangefirstlove** [comment]
> v1.3.5로 수정하였습니다. `pip install srtgo -U`로 버전이 1.3.5로 올라가는지 확인해주세요~.

확인했습니다. 빠른 처리 감사드립니다^^

**Comment by zwl051000** [comment]
안녕하세요. 저도 프로그램 너무 잘 쓰고 편하게 SRT 예매하고 있습니다. 감사합니다.
전 두가지 에러가 발견되어 공유드립니다.
우선 SRT 열차검색할때 에러가 뜹니다. ㅡㅜ
그리고 예매 후 결제가 자동적으로 안되고 505 에러가 뜹니다.
확인 부탁드리고 에러 수정해주시면 너무 감사하겠습니다.
![예매후 에러](https://github.com/user-attachments/assets/004ffbac-9ad0-4340-9c0c-f30748ac53e5)
![SRT 예매확인취소 에러](https://github.com/user-attachments/assets/f651fcc8-e943-43eb-a667-6027fa63d1a9)
