### ISSUE TITLE
[SRTResponseError] 예매시 로그인 에러

### ISSUE THREAD

**Issue by happycatsforever** [lapis42/srtgo#40]
안녕하세요 개발자님 ! 
예매하는데 로그인 에러가 뜨네요

![화면 캡처 2024-12-18 103925](https://github.com/user-attachments/assets/6a2909ae-8b63-4432-a6ce-df9c8a90f0d7)
![KakaoTalk_20241218_104146959](https://github.com/user-attachments/assets/ed5199b8-c4ff-4b9b-9770-883c684bc954)
 
- `pip install git+https://github.com/lapis42/srtgo -U` 로 가장 최신 버전으로 업데이트 했습니다.
  -  가장 최신버전 코드로 내려받아서 실행했습니다.
- SRT 1대 / 1명 / 일반실 / 예매시카드결제 N 로 예약했습니다 (로그인정보 입력되어있습니다.)
- 처음에 `예매 대기 중` 로딩 뜨다가 한참있다가(에러가 뜨는 시기는 불규칙합니다) 표가 잡힌건지 할때마다 저렇게 뜹니다.

**Comment by lapis42** [comment]
네 감사합니다. 제가 장시간 테스트를 하지 않아서 그런지 에러 재현이 어렵네요.
우선 문제가 될 수 있는 error handling 부분 및 SRT 예매 부분을 보강하긴 하였습니다.
업데이트 및 테스트 후 결과를 알려주시면 감사하겠습니다.

**Comment by happycatsforever** [comment]
업데이트 받아서 다시 해봤습니다
SRT 1대만 선택할때는 계속 티켓이 안잡혀서 에러/예매성공 테스트는 못해봤습니다
일단 SRT2대 선택해서 다시 실행시켜봤는데 예매 아주 잘 됩니다!
안내 감사합니다 :)

**Comment by lapis42** [comment]
감사합니다. 제 환경에서는 재현이 어렵기도 하고, 현재 버전에서는 큰 문제가 없는 것 같아 여기서 close하겠습니다.
