### ISSUE TITLE
SRT 예약대기, 일반예매 선택가능하도록 요청 및 텔레그램알림 오

### ISSUE THREAD

**Issue by ktr218** [lapis42/srtgo#41]
![image](https://github.com/user-attachments/assets/3da7d789-a954-4fcc-80ae-01703e31641f)
 
예약대기 텔레그램 알림시 알림 오류 및

예약대기와 일반예매 선택할수 있도록 부탁드립니다.

**Comment by lapis42** [comment]
1. 어떤 상황에서 에러가 발생하였는지, 어떤 빈도로 발생하는지 알려주셨으면 합니다.
2. 예약 대기는 특실/일반실 예매가 불가능한 상황에서 진행하도록 하였는데 어떤 상황에서 선택이 필요한지 알려주시면 감사하겠습니다. 꼭 이 기능이 필요하시다면 이전 버전으로 설치하시면 현재도 사용 가능합니다 (v2.0.1).

**Comment by DD311** [comment]
엇, 저 오류 저도 떴습니다. SRT 예약대기가 잡힐 경우 저렇게 알림이 옵니다. (예약 대기는 정상적으로 되고, 알림만 오류)
+) ktr218님, 예약대기가 걸리는 기간에는 일반실 자리가 떠도 먼저 예약대기를 걸어 놓은 사람에게 우선 배정됩니다. 즉, 예약 대기가 된다면 예약 대기를 하시는 게 훨씬 빨리 자리를 잡을 수 있어요. 예약대기 걸어 놓은 사람들에게 표 배정이 다 끝난 후에 일반 예매가 풀립니다. (예약 대기는 출발일 2일 전까지 걸 수 있음)

**Comment by ktr218** [comment]
감사합니다 ㅎㅎ


네이버 메일 앱에서 보냈습니다.

-----Original Message-----
보낸사람: "DD311" ***@***.***>
받는사람: "lapis42/srtgo" ***@***.***>
참조: "ktr218" ***@***.***>,"Author" ***@***.***>
날짜:2024.12.20 오후 10:58:19 (GMT+09:00)
제목: Re: [lapis42/srtgo] SRT 예약대기, 일반예매 선택가능하도록 요청 및 텔레그램알림 오 (Issue #41)

엇, 저 오류 저도 떴습니다. SRT 예약대기가 잡힐 경우 저렇게 알림이 옵니다. (예약 대기는 정상적으로 되고, 알림만 오류)
+) ktr218님, 예약대기가 걸리는 기간에는 일반실 자리가 떠도 먼저 예약대기를 걸어 놓은 사람에게 우선 배정됩니다. 즉, 예약 대기가 된다면 예약 대기를 하시는 게 훨씬 빨리 자리를 잡을 수 있어요. 예약대기 걸어 놓은 사람들에게 표 배정이 다 끝난 후에 일반 예매가 풀립니다. (예약 대기는 출발일 2일 전까지 걸 수 있음)
