### ISSUE TITLE
SRT 역 추가 문의

### ISSUE THREAD

**Issue by DD311** [lapis42/srtgo#43]
안녕하세요.
혹시 SRT 역에 '창원중앙' 역 추가 가능할까요?
창원역은 있는데 창원중앙은 없어서 문의드려 봅니다.
좋은 코드 정말 정말 감사합니다.

**Comment by lapis42** [comment]
v2.1.1에서 수정하였습니다. 역설정을 다시 하시기 진행하시기 바랍니다.
