### ISSUE TITLE
예약대기 불가능 날짜로 바뀌면 재구동이 필요한 게 맞나요?

### ISSUE THREAD

**Issue by DD311** [lapis42/srtgo#44]
![dd](https://github.com/user-attachments/assets/aae0cc77-b168-447a-bc49-a5434af89e56)

안녕하세요, 개발자님.
자정을 기점으로 SRT 예약대기 불가능 날짜로 바뀌면 위와 같은 메시지가 뜨면서 예약시도가 멈춥니다.
[계속하시겠습니까? y/N] 라고 떠서 y를 눌러도 또 예약대기를 시도하는지 동일한 메시지가 노출됩니다.
프롬프트를 껐다 켜서 다시 구동하면 잘 되기는 합니다만, 혹시 이것도 수정이 필요한 일인가 하여 기재합니다.
항상 감사합니다.

**Comment by lapis42** [comment]
Resolved by v2.1.2
