### ISSUE TITLE
일반실만 지정했으나 특실 예매됨

### ISSUE THREAD

**Issue by DD311** [lapis42/srtgo#46]
![IMG_7176](https://github.com/user-attachments/assets/a713c2cb-1145-4b5e-81d3-7e56a95a8906)

안녕하세요, 개발자님. 노고가 많으십니다.
캡처에서처럼 ‘일반실만‘으로 지정하고 예약 진행하였는데 특실로 예약되었습니다. 
수정이 가능한 부분인지 확인 부탁드려도 될까요?
늘 감사합니다.

**Comment by lapis42** [comment]
예약대기 기간에는 객실 종류를 고르는 것이 어렵습니다. 만일 예약대기 기능이 없는 버전을 원하시면 `pip install srtgo=2.0.1`로 이전 버전을 설치하여 사용하시면 됩니다.

* 개인적인 용도로 만든 프로그램으로, 모든분의 요구를 맞춰드릴 수 없는 점 양해바랍니다. 필요에 맞게 앱이나 크롬 확장 프로그램 등을 활용하시는 것을 추천합니다.

**Comment by DD311** [comment]
아하, 그렇군요. 잘 몰랐습니다. 사실 무관하나 혹시 오류인가 싶어 이슈 올렸습니다. 답변해 주셔서 감사합니다. 좋은 하루 보내세요.

**Comment by lapis42** [comment]
네 이해해주셔서 감사합니다. 저는 예약대기 기능 이후 예매가 훨씬 수월해진 것 같습니다.
