### ISSUE TITLE
접속이 원할하지 않습니다.

### ISSUE THREAD

**Issue by daniel00** [lapis42/srtgo#47]
안녕하세요 개발자님.
그동안 잘 사용 했었는데 오늘은 다음과 같은 에러가 발생하네요. srt앱으로는 접속 예매가 가능합니다.
좋은 프로그램 만들어주셔서 감사합니다.

안드로이드 termux에서 실행시켰고, 
전화번호 회원번호 모두 동일한 에러가 출력됩니다.

![Screenshot_20241226_094121_Termux](https://github.com/user-attachments/assets/152ec759-7e25-42ff-b9fa-504b19106be9)

**Comment by lapis42** [comment]
Resolved by #48

**Comment by lapis42** [comment]
v2.1.3으로 업데이트 하였습니다. 다음부터는 버그 리포트 양식을 따라주셨으면 합니다.

**Comment by daniel00** [comment]
> v2.1.3으로 업데이트 하였습니다. 다음부터는 버그 리포트 양식을 따라주셨으면 합니다.

네. 감사합니다.
