### ISSUE TITLE
경로우대 설정

### ISSUE THREAD

**Issue by zwl051000** [lapis42/srtgo#6]
안녕하세요. 저희 아버지 예약건 때문에 경로로 설정해서 예약하고 싶습니다.
481~483줄에 있는 내용을 수정해야 할것 같은데 아무리 제가 코드를 건드려도 잘 되는것 같지 않아(초보라서...ㅡㅜ)
하는 방법 설명을 댓글로 요청 드려도 될까요? 미리 감사드립니다. ^^

**Comment by lapis42** [comment]
예매만 하시고 (결제 X), 홈페이지에 접속하셔서 예약변경을 하실 수 있습니다 (성인 -> 경로). 급한대로 이렇게 해결해보시면 좋을 것 같습니다.

**Comment by lapis42** [comment]
아니면 Line 17을
`from SRT.passenger import Passenger, Adult, Child, Senior`로 수정하시고

Line 303을 
`passengers.append((Senior if rail_type == "SRT" else ChildPassenger)(info["child"]))`로 수정하시면 됩니다.

**Comment by zwl051000** [comment]
감사합니다. 말씀대로 수정해놨는데 아래 메시지가 뜨네요. 
나중에 확인되실때 할수 있는 방법 공유해주시면 너무 감사하겠습니다. ^^
![20240912_204130](https://github.com/user-attachments/assets/19f454d9-c327-4c59-ad8e-a1bf0cb3b3fe)

**Comment by lapis42** [comment]
네 수정에 조금 시간이 걸릴 것 같아 우선은 예매 후 홈페이지에서 예약변경으로 승차종류 변경 후 결제를 하시는 것이 가장 편하실 것 같습니다.

**Comment by zwl051000** [comment]
늦은 시간에도 친절히 답변해주셔서 감사드립니다.
말씀해주신대로 업데이트 기다리겠습니다. 
마지막으로 항상 좋은 자료에 진심으로 감사드립니다. ^^
