### ISSUE TITLE
SSL CERT VERIFICATION 에러

### ISSUE THREAD

**Issue by wkdwnghwkd** [lapis42/srtgo#7]
안녕하세요, KTX 표를 예매하려고 확인하던 중에 아래 에러가 발생했습니다.

requests.exceptions.SSLError: HTTPSConnectionPool(host='smart.letskorail.com', port=443): Max retries exceeded with url: /classes/com.korail.mobile.common.code.do (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))

KTX 예매 기능이 정상적으로 작동하고 있으실까요?

확인부탁드립니다!

**Comment by wkdwnghwkd** [comment]
흠 일단 로컬에서 해당 부분 "verify=false" 를 추가해서 넘어가긴 했는데,,, 

예약되는 시점에 로그인 정보를 인식하지 못하는거 같네요..

![image](https://github.com/user-attachments/assets/9d882860-6f32-4205-bc27-0f39c2811663)

**Comment by lapis42** [comment]
로그인 정보가 맞는지 한 번 확인하시면 좋을 것 같습니다! 방금 테스트했을 때 예약까지는 잘 진행이 되었습니다.

**Comment by wkdwnghwkd** [comment]
아,,, 로그인 정보를 제가 두번 연속으로 잘못넣었네요! 감사합니다!

**Comment by lapis42** [comment]
감사합니다!
