### ISSUE TITLE
KTX 열차 시간당 목록 갯수를 늘려주셨으면 합니다.

### ISSUE THREAD

**Issue by Lskyz** [lapis42/srtgo#8]
승객량 많은 노선의 경우 시간당 목록갯수가 15~20 개 정도 되는데

여기에 무궁화,itx마음까지 끼어있고 인접역 시간대까지 조회가되어서 현재 열차 목록 갯수로는 중후반 시간대는 조회가 불가능 한게 아쉽습니다. 그렇기에 늘렸으면 좋겠고

목록 늘리기가 좀 그렇다면 열차 종류에 따라 조회가 가능하도록 고려해주셨으면 합니다.  

그리고 ktx 어린이,경로우대도 있는데 장애인 우대도 생겼으면 좋겠습니다.

**Comment by lapis42** [comment]
- KTX만 조회 가능하도록 업데이트 하였습니다. 긴 시간 조회하는 것은 가능은 하지만, 지연시간이 길어 조회 후 예매를 시도했을 때 성공률이 떨어집니다.
- 장애인 우대는 [korail2](https://github.com/carpedm20/korail2) 모듈에서 구현이 되어 있지 않아 추가가 어렵습니다. 예매 후 코레일 홈페이지에서 예약변경하시는 것을 추천드립니다.

**Comment by Lskyz** [comment]
Ktx만 조회 되도록 업데이트 해주셨다고 하셔서 1.38 버전 파일을 내려받아서 
pip install srtgo -U 해주고 1.38버전 설치되었다고 뜨는데도 여전히 무궁화 , 마음도 같이 뜹니다.. 왜그럴까요?
